#开发环境
#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql1234
  thymeleaf:
    prefix: classpath:/templates/
#配置mybatis的信息
#spring继承mybatis环境
#POJO别名扫描的包
mybatis:
  type-aliases-package: com.ucar.training.dao
  #加载mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
#mybatis整合springboot日志输出
logging:
  level:
    root: info
    com.patrickstar.blog.dao: debug
  file:
    path: log/blog-devlop.log